/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Books */
        get: operations["list_books_api_books_get"];
        put?: never;
        /** Create Book */
        post: operations["create_book_api_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book Summary */
        get: operations["get_book_summary_api_books__book_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Book */
        delete: operations["delete_book_api_books__book_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_api_books__book_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/steps/{step_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Step */
        post: operations["run_step_api_books__book_id__steps__step_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/pages/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page Workspace */
        get: operations["get_page_workspace_api_books__book_id__pages_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/pages/source/{source_pdf_page}.webp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Page Preview */
        get: operations["get_source_page_preview_api_books__book_id__pages_source__source_pdf_page__webp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/pages/revisions/{revision_id}/assets/{asset_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page Asset */
        get: operations["get_page_asset_api_books__book_id__pages_revisions__revision_id__assets__asset_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/proofread/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_books__book_id__proofread_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/proofread/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: operations["publish_api_books__book_id__proofread_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/proofread/check-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Text */
        post: operations["check_text_api_books__book_id__proofread_check_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/audio/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_books__book_id__audio_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/audio/revisions/{revision_id}/assets/{asset_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_books__book_id__audio_revisions__revision_id__assets__asset_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/export/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_books__book_id__export_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/export/revisions/{revision_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_books__book_id__export_revisions__revision_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Storage */
        get: operations["get_storage_api_storage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/recalculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recalculate Storage */
        post: operations["recalculate_storage_api_storage_recalculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/migrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Storage Migration */
        post: operations["start_storage_migration_api_storage_migrations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storage/migrations/{migration_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Storage Migration */
        get: operations["get_storage_migration_api_storage_migrations__migration_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveAttempt */
        ActiveAttempt: {
            /** Job Id */
            job_id: string;
            /** Params Hash */
            params_hash: string;
            /** Input Fingerprint */
            input_fingerprint: string;
            base_status: components["schemas"]["StepStatus"];
            base_stale_reason?: components["schemas"]["InvalidationReason"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id: string;
        };
        /**
         * AttemptStatus
         * @enum {string}
         */
        AttemptStatus: "succeeded" | "failed" | "cancelled" | "interrupted";
        /** AttemptSummary */
        AttemptSummary: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["AttemptStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            error?: components["schemas"]["PipelineErrorInfo"] | null;
        };
        /** AudioParams */
        AudioParams: {
            voice?: components["schemas"]["VoiceConfig"];
            /**
             * Opus Bitrate Kbps
             * @default 32
             */
            opus_bitrate_kbps: number;
            /**
             * Tempo
             * @default 0.9
             */
            tempo: number;
            /**
             * Language
             * @default en
             */
            language: string;
            /**
             * Sentence Ids
             * @default []
             */
            sentence_ids: string[];
            /** Base Audio Revision */
            base_audio_revision?: string | null;
        };
        /** AudioSentenceReport */
        AudioSentenceReport: {
            /** Sentence Id */
            sentence_id: string;
            /** Audio Path */
            audio_path?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Word Timing */
            word_timing?: components["schemas"]["AudioWordTiming"][] | null;
            provider?: components["schemas"]["TtsProviderKind"] | null;
            /**
             * Suspect Tts
             * @default false
             */
            suspect_tts: boolean;
            /** Error Code */
            error_code?: string | null;
        };
        /** AudioWordTiming */
        AudioWordTiming: {
            /** Word */
            word: string;
            /** T Start */
            t_start: number;
            /** T End */
            t_end: number;
        };
        /** AudioWorkspaceResponse */
        AudioWorkspaceResponse: {
            /** Proofread Revision Id */
            proofread_revision_id: string;
            /** Audio Revision Id */
            audio_revision_id?: string | null;
            params: components["schemas"]["AudioParams"];
            /** Original Audio Path */
            original_audio_path?: string | null;
            /** Sentences */
            sentences: components["schemas"]["AudioWorkspaceSentence"][];
        };
        /** AudioWorkspaceSentence */
        AudioWorkspaceSentence: {
            sentence: components["schemas"]["OcrSentence"];
            report?: components["schemas"]["AudioSentenceReport"] | null;
        };
        /**
         * AutoProofreadParams
         * @description Immutable commit payload for the human OCR proofread workspace.
         *
         *     ``accept_ocr_draft`` remains as a compatibility path for existing M2 automation;
         *     interactive clients submit the complete edited sentence table instead.
         */
        AutoProofreadParams: {
            /**
             * Accept Ocr Draft
             * @default false
             */
            accept_ocr_draft: boolean;
            /** Source Ocr Revision */
            source_ocr_revision?: string | null;
            /** Sentences */
            sentences?: components["schemas"]["OcrSentence"][];
            /** Confirmed Pages */
            confirmed_pages?: number[];
        };
        /** Body_create_book_api_books_post */
        Body_create_book_api_books_post: {
            /**
             * Pdf
             * @description 要处理的 PDF 文件
             */
            pdf: string;
            /**
             * Original Audio
             * @description 可选的绘本原音 MP3
             */
            original_audio?: string | null;
        };
        /** BoundingBox */
        BoundingBox: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Capabilities */
            capabilities: components["schemas"]["CapabilityStatus"][];
        };
        /**
         * CapabilityGroup
         * @enum {string}
         */
        CapabilityGroup: "local" | "cloud";
        /** CapabilityStatus */
        CapabilityStatus: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            group: components["schemas"]["CapabilityGroup"];
            /** Available */
            available: boolean;
            /** Detail */
            detail: string;
        };
        /** ExportCheck */
        ExportCheck: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "warning" | "error";
            /** Detail */
            detail: string;
        };
        /** ExportPackageInfo */
        ExportPackageInfo: {
            /** Filename */
            filename: string;
            /** Page Count */
            page_count: number;
            /** Sentence Count */
            sentence_count: number;
            /** Word Timing Sentence Count */
            word_timing_sentence_count: number;
            /** Audio Provider Counts */
            audio_provider_counts?: {
                [key: string]: number;
            };
            /** Size Bytes */
            size_bytes?: number | null;
            /** Sha256 */
            sha256?: string | null;
        };
        /** ExportWorkspaceResponse */
        ExportWorkspaceResponse: {
            /** Ready */
            ready: boolean;
            /** Suggested Title */
            suggested_title: string;
            /** Checks */
            checks: components["schemas"]["ExportCheck"][];
            package: components["schemas"]["ExportPackageInfo"];
            /** Export Revision Id */
            export_revision_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvalidationReason */
        InvalidationReason: {
            source_step: components["schemas"]["StepId"];
            /** Old Output Fingerprint */
            old_output_fingerprint?: string | null;
            /** New Output Fingerprint */
            new_output_fingerprint: string;
            /** Reason */
            reason: string;
            /**
             * Invalidated At
             * Format: date-time
             */
            invalidated_at: string;
        };
        /** JobSnapshot */
        JobSnapshot: {
            /** Job Id */
            job_id: string;
            /** Book Id */
            book_id: string;
            step_id: components["schemas"]["StepId"];
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /** Message */
            message: string;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            error?: components["schemas"]["PipelineErrorInfo"] | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "cancelling" | "succeeded" | "failed" | "cancelled" | "interrupted";
        /** OcrSentence */
        OcrSentence: {
            /** Id */
            id: string;
            /** Page No */
            page_no: number;
            /** Seq */
            seq: number;
            /** Text */
            text: string;
            bbox: components["schemas"]["BoundingBox"];
            /** Shared Bbox */
            shared_bbox: boolean;
            status: components["schemas"]["SentenceStatus"];
            /**
             * Suspect Words
             * @default []
             */
            suspect_words: components["schemas"]["SuspectWord"][];
        };
        /** OutputFile */
        OutputFile: {
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Sha256 */
            sha256: string;
        };
        /** PageCrop */
        PageCrop: {
            /**
             * Top
             * @default 0
             */
            top: number;
            /**
             * Right
             * @default 0
             */
            right: number;
            /**
             * Bottom
             * @default 0
             */
            bottom: number;
            /**
             * Left
             * @default 0
             */
            left: number;
        };
        /** PageDecision */
        PageDecision: {
            mode: components["schemas"]["PageMode"];
            /** Split Ratio */
            split_ratio?: number | null;
            /**
             * Rotate
             * @default 0
             * @enum {integer}
             */
            rotate: 0 | 90 | 180 | 270;
            crop_pct?: components["schemas"]["PageCrop"];
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
        };
        /** PageDecisionOverride */
        PageDecisionOverride: {
            /** Source Pdf Page */
            source_pdf_page: number;
            decision: components["schemas"]["PageDecision"];
        };
        /** PageDetect */
        PageDetect: {
            /** Suspect Split */
            suspect_split: boolean;
            /** Confidence */
            confidence: number;
            /** Suggested Split Ratio */
            suggested_split_ratio?: number | null;
        };
        /**
         * PageMode
         * @enum {string}
         */
        PageMode: "keep" | "split_lr";
        /** PageOutput */
        PageOutput: {
            /** Page No */
            page_no: number;
            region: components["schemas"]["PageRegion"];
            /** Ocr Image */
            ocr_image: string;
            /** Page Image */
            page_image: string;
            /** Thumbnail */
            thumbnail: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** PagePlan */
        PagePlan: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Source Pdf Sha256 */
            source_pdf_sha256: string;
            /** Source Pdf Page Count */
            source_pdf_page_count: number;
            params: components["schemas"]["PageProcessParams"];
            /** Pages */
            pages: components["schemas"]["PagePlanEntry"][];
        };
        /** PagePlanEntry */
        PagePlanEntry: {
            /** Source Pdf Page */
            source_pdf_page: number;
            source_size_pt: components["schemas"]["SourcePageSize"];
            detect: components["schemas"]["PageDetect"];
            decision: components["schemas"]["PageDecision"];
            /** Outputs */
            outputs: components["schemas"]["PageOutput"][];
        };
        /** PageProcessParams */
        PageProcessParams: {
            /** @default clear */
            quality: components["schemas"]["PageQuality"];
            /**
             * Reading Long Edge
             * @default 2000
             */
            reading_long_edge: number;
            /**
             * Webp Quality
             * @default 82
             */
            webp_quality: number;
            /**
             * Ocr Dpi
             * @default 300
             */
            ocr_dpi: number;
            /**
             * Detection Dpi
             * @default 96
             */
            detection_dpi: number;
            /**
             * Thumbnail Long Edge
             * @default 360
             */
            thumbnail_long_edge: number;
            /**
             * Thumbnail Quality
             * @default 78
             */
            thumbnail_quality: number;
            /**
             * Split Detection Enabled
             * @default true
             */
            split_detection_enabled: boolean;
            /**
             * Wide Ratio Threshold
             * @default 1.3
             */
            wide_ratio_threshold: number;
            /**
             * Center Window Start
             * @default 0.4
             */
            center_window_start: number;
            /**
             * Center Window End
             * @default 0.6
             */
            center_window_end: number;
            /**
             * Confirmation Confidence
             * @default 70
             */
            confirmation_confidence: number;
            /**
             * Page Decisions
             * @default []
             */
            page_decisions: components["schemas"]["PageDecisionOverride"][];
        };
        /**
         * PageQuality
         * @enum {string}
         */
        PageQuality: "clear" | "balanced" | "compact";
        /**
         * PageRegion
         * @enum {string}
         */
        PageRegion: "full" | "left" | "right";
        /** PageWorkspaceResponse */
        PageWorkspaceResponse: {
            /** Revision Id */
            revision_id: string;
            plan: components["schemas"]["PagePlan"];
            /** Ocr Revision Id */
            ocr_revision_id?: string | null;
            /**
             * Sentences
             * @default []
             */
            sentences: components["schemas"]["OcrSentence"][];
        };
        /** PipelineErrorInfo */
        PipelineErrorInfo: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** PipelineSource */
        PipelineSource: {
            /** Pdf Path */
            pdf_path: string;
            /** Pdf Sha256 */
            pdf_sha256: string;
            /** Original Audio Path */
            original_audio_path?: string | null;
            /** Original Audio Sha256 */
            original_audio_sha256?: string | null;
        };
        /** PipelineState */
        PipelineState: {
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
            /** Book Id */
            book_id: string;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            source: components["schemas"]["PipelineSource"];
            /** Steps */
            steps: {
                [key: string]: components["schemas"]["StepState"];
            };
        };
        /** ProofreadPage */
        ProofreadPage: {
            /** Page No */
            page_no: number;
            /** Image */
            image: string;
            /** Thumbnail */
            thumbnail: string;
        };
        /** ProofreadTextCheckRequest */
        ProofreadTextCheckRequest: {
            /** Text */
            text: string;
        };
        /** ProofreadTextCheckResponse */
        ProofreadTextCheckResponse: {
            /**
             * Suspect Words
             * @default []
             */
            suspect_words: components["schemas"]["SuspectWord"][];
        };
        /** ProofreadWorkspaceResponse */
        ProofreadWorkspaceResponse: {
            /** Pages Revision Id */
            pages_revision_id: string;
            /** Ocr Revision Id */
            ocr_revision_id: string;
            /** Proofread Revision Id */
            proofread_revision_id?: string | null;
            /** Pages */
            pages: components["schemas"]["ProofreadPage"][];
            /** Sentences */
            sentences: components["schemas"]["OcrSentence"][];
            /**
             * Confirmed Pages
             * @default []
             */
            confirmed_pages: number[];
        };
        /** RunSkippedResponse */
        RunSkippedResponse: {
            /**
             * Disposition
             * @default skipped
             */
            disposition: string;
            state: components["schemas"]["PipelineState"];
        };
        /** RunStartedResponse */
        RunStartedResponse: {
            /**
             * Disposition
             * @default started
             */
            disposition: string;
            /** Job Id */
            job_id: string;
        };
        /** RunStepRequest */
        RunStepRequest: {
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /**
         * SentenceStatus
         * @enum {string}
         */
        SentenceStatus: "sentence" | "needs_review";
        /** SourcePageSize */
        SourcePageSize: {
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /**
         * StepId
         * @enum {string}
         */
        StepId: "pages" | "ocr" | "proofread" | "audio" | "export";
        /** StepState */
        StepState: {
            /** @default pending */
            status: components["schemas"]["StepStatus"];
            success?: components["schemas"]["StepSuccess"] | null;
            active_attempt?: components["schemas"]["ActiveAttempt"] | null;
            last_attempt?: components["schemas"]["AttemptSummary"] | null;
            stale_reason?: components["schemas"]["InvalidationReason"] | null;
        };
        /**
         * StepStatus
         * @enum {string}
         */
        StepStatus: "pending" | "running" | "done" | "failed" | "stale";
        /** StepSuccess */
        StepSuccess: {
            /** Revision Id */
            revision_id: string;
            /** Output Root */
            output_root: string;
            /** Params Hash */
            params_hash: string;
            /** Input Fingerprint */
            input_fingerprint: string;
            /** Output Fingerprint */
            output_fingerprint: string;
            /** Outputs */
            outputs: components["schemas"]["OutputFile"][];
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
        };
        /** StorageInfo */
        StorageInfo: {
            /** Workspace Root */
            workspace_root: string;
            /** Managed By */
            managed_by: string;
            /** Workspace Count */
            workspace_count: number;
            /** Used Bytes */
            used_bytes: number;
            /** Disk Total Bytes */
            disk_total_bytes: number;
            /** Disk Free Bytes */
            disk_free_bytes: number;
        };
        /**
         * StorageMigrationPhase
         * @enum {string}
         */
        StorageMigrationPhase: "queued" | "preflight" | "copying" | "verifying" | "switched" | "failed";
        /** StorageMigrationRequest */
        StorageMigrationRequest: {
            /** Target Root */
            target_root: string;
        };
        /** StorageMigrationStatus */
        StorageMigrationStatus: {
            /** Migration Id */
            migration_id: string;
            /** Target Root */
            target_root: string;
            phase: components["schemas"]["StorageMigrationPhase"];
            /** Progress */
            progress: number;
            /** Message */
            message: string;
            /**
             * Copied Bytes
             * @default 0
             */
            copied_bytes: number;
            /**
             * Total Bytes
             * @default 0
             */
            total_bytes: number;
            /**
             * Restart Required
             * @default false
             */
            restart_required: boolean;
            error?: components["schemas"]["PipelineErrorInfo"] | null;
        };
        /**
         * SuspectKind
         * @enum {string}
         */
        SuspectKind: "spelling" | "proper_noun";
        /** SuspectWord */
        SuspectWord: {
            /** Word */
            word: string;
            kind: components["schemas"]["SuspectKind"];
        };
        /**
         * TtsProviderKind
         * @enum {string}
         */
        TtsProviderKind: "voxcpm";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceConfig */
        VoiceConfig: {
            /** @default design */
            mode: components["schemas"]["VoiceMode"];
            /**
             * Description
             * @default warm female kindergarten teacher, slow and clear
             */
            description: string;
            /** Reference Wav Path */
            reference_wav_path?: string | null;
        };
        /**
         * VoiceMode
         * @enum {string}
         */
        VoiceMode: "design" | "clone";
        /**
         * WorkspaceLifecycleStatus
         * @enum {string}
         */
        WorkspaceLifecycleStatus: "in_progress" | "running" | "failed" | "stale" | "completed" | "corrupt";
        /** WorkspaceListResponse */
        WorkspaceListResponse: {
            /** Workspaces */
            workspaces: components["schemas"]["WorkspaceSummary"][];
            /** Total Size Bytes */
            total_size_bytes: number;
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /** Book Id */
            book_id: string;
            /** Display Name */
            display_name: string;
            /** Source Filename */
            source_filename?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Opened At */
            last_opened_at?: string | null;
            lifecycle_status: components["schemas"]["WorkspaceLifecycleStatus"];
            current_step: components["schemas"]["StepId"];
            step_status?: components["schemas"]["StepStatus"] | null;
            /** Completed Steps */
            completed_steps: number;
            /** Continue Path */
            continue_path: string;
            /** Page Count */
            page_count?: number | null;
            /** Sentence Count */
            sentence_count?: number | null;
            /**
             * Exported
             * @default false
             */
            exported: boolean;
            /** Size Bytes */
            size_bytes: number;
            error?: components["schemas"]["PipelineErrorInfo"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_books_api_books_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create_book_api_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_book_api_books_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineState"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_book_summary_api_books__book_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    delete_book_api_books__book_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_state_api_books__book_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineState"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    run_step_api_books__book_id__steps__step_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                step_id: components["schemas"]["StepId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunStepRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSkippedResponse"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStartedResponse"] | components["schemas"]["RunSkippedResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSnapshot"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSnapshot"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_page_workspace_api_books__book_id__pages_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageWorkspaceResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_source_page_preview_api_books__book_id__pages_source__source_pdf_page__webp_get: {
        parameters: {
            query?: {
                max_edge?: number;
            };
            header?: never;
            path: {
                book_id: string;
                source_pdf_page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_page_asset_api_books__book_id__pages_revisions__revision_id__assets__asset_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                revision_id: string;
                asset_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_workspace_api_books__book_id__proofread_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProofreadWorkspaceResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    publish_api_books__book_id__proofread_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoProofreadParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSkippedResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    check_text_api_books__book_id__proofread_check_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProofreadTextCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProofreadTextCheckResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_workspace_api_books__book_id__audio_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AudioWorkspaceResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_asset_api_books__book_id__audio_revisions__revision_id__assets__asset_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                revision_id: string;
                asset_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_workspace_api_books__book_id__export_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportWorkspaceResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    download_api_books__book_id__export_revisions__revision_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    get_storage_api_storage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageInfo"];
                };
            };
        };
    };
    recalculate_storage_api_storage_recalculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageInfo"];
                };
            };
        };
    };
    start_storage_migration_api_storage_migrations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorageMigrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageMigrationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_storage_migration_api_storage_migrations__migration_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                migration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageMigrationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
